
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo-ibc_development
test:
  <<: *default
  database: todo-ibc_test

production:
  <<: *default
  database: <%= Rails.application.credentials[:production][:aws][:RDS_DB_NAME] %>
  username: <%= Rails.application.credentials[:production][:aws][:RDS_USERNAME] %>
  password: <%= Rails.application.credentials[:production][:aws][:RDS_PASSWORD] %>
  host: <%= Rails.application.credentials[:production][:aws][:RDS_HOSTNAME] %>
  port: <%= Rails.application.credentials[:production][:aws][:RDS_PORT] %>
